FROM docker.io/pentoolinux/pentoo-core:latest
ADD portage_and_overlay.tar.xz /

# setup FEATURES and use flags
RUN echo 'FEATURES="-ipc-sandbox -network-sandbox -pid-sandbox"' >> /etc/portage/make.conf

# install the minimal metapackage
RUN sed -i 's#-livecd#-drivers -pulseaudio -vnc opencl rfctf-minimal#' /etc/portage/make.conf && \
  emerge --getbinpkg=y --buildpkg=n --jobs=$(nproc) --deep --update --newuse pentoo/rfctf-client && \
  # remove build deps
  emerge --depclean --with-bdeps=n --jobs=$(nproc) && \
  # rm all the files we don't want
  rm -rf /var/cache/{binpkgs,distfiles}/* /var/db/repos/* /usr/share/{man,doc}/*

# install the actual metapackage
ADD portage_and_overlay.tar.xz /
RUN sed -i 's#rfctf-minimal#rfctf-sdr rfctf-minimal#' /etc/portage/make.conf && \
  emerge --getbinpkg=y --buildpkg=n --jobs=$(nproc) --deep --update --newuse pentoo/rfctf-client && \
  # remove build deps
  emerge --depclean --with-bdeps=n --jobs=$(nproc) && \
  # rm all the files we don't want
  rm -rf /var/cache/{binpkgs,distfiles}/* /var/db/repos/* /usr/share/{man,doc}/*
RUN [ -z "$(portageq match / '<net-wireless/bladerf-firmware-2.6.0')" ]
RUN [ -z "$(portageq match / '<net-wireless/bladerf-fpga-0.16.0')" ]
RUN [ -z "$(portageq match / '<net-wireless/gnuradio-3.11_pre20260615-r1')" ]
RUN [ -z "$(portageq match / '<net-wireless/gr-tenna-0.0_p20260506" ]

# setup challengectl
ADD "https://api.github.com/repos/rfhs/challengectl/commits?per_page=1" latest_commit
WORKDIR /root/
RUN git clone https://github.com/rfhs/challengectl.git --depth 1

WORKDIR /root/challengectl/
CMD ["/bin/bash"]
ENTRYPOINT []
