#!/bin/sh
VERS="0.16"
DISTRO="blackarch"
docker build . --pull -f "Dockerfile.${DISTRO}" -t rfhs/${DISTRO}:${VERS}
docker tag rfhs/${DISTRO}:${VERS} rfhs/${DISTRO}:latest
#docker push rfhs/${DISTRO}
#docker push rfhs/${DISTRO}:latest
