#!/bin/sh
VERS="0.23"
DISTRO="pentoo"
#./make_gentoo_cache.sh
docker build . --pull -f "Dockerfile.${DISTRO}" -t rfhs/${DISTRO}:${VERS}
docker tag rfhs/${DISTRO}:${VERS} rfhs/${DISTRO}:latest
if [ "$(hostname)" = "Nu" ] ; then
  docker push rfhs/${DISTRO}
  docker push rfhs/${DISTRO}:${VERS}
  docker push rfhs/${DISTRO}:latest
fi
