#!/bin/sh

# First we check startup services worked
# Or we would, except EXITED looks the same success or failure so there is no point
# In this case it's safe, because ssh won't come up unless these two succeeded
#for exited in sshdir sshkeys; do
#	if [ "$(supervisorctl status ${exited} | awk '{print $2}')" != "EXITED" ]; then
#		supervisorctl status
#		exit 1
#	fi
#done

# Next we check runtime services think they are running
for running in X11 novnc sshd x11vnc xfce; do
	if [ "$(supervisorctl status ${running} | awk '{print $2}')" != "RUNNING" ]; then
		supervisorctl status
		exit 1
	fi
done

# Then we check the expected listening ports are actually listening
for port in 22 8080; do
	if ! ss -nlt | grep -q "0.0.0.0:${port}"; then
		printf "Nothing is listening on port %s" "${port}"
		ss -nltp
		exit 1
	fi
done

printf "Everything looks good.\n"
true
