#!/bin/sh

set -eu

# Check for required packages/commands being installed
if [ "${1:-}" = "excessive" ]; then
  if [ ! -x "$(command -v notify-send 2>&1)" ]; then
    printf 'notify-send required but not found\n'
    exit 1
  fi
  if [ ! -x "$(command -v supervisorctl 2>&1)" ]; then
    printf 'supervisorctl required but not found\n'
    exit 1
  fi
  if [ ! -x "$(command -v aircrack-ng 2>&1)" ]; then
    printf 'aircrack-ng required but not found\n'
    exit 1
  else
    printf 'Testing aircrack-ng for 30 seconds...\n'
    nice -n 19 aircrack-ng -S -Z 30
    printf 'Test passed\n'
  fi
fi

# Next we check runtime services think they are running
# sshdir and sshkeys don't have to be checked, only sshd
if [ "$(supervisorctl status sshd X11 xfce x11vnc novnc | grep -c 'RUNNING')" -lt "5" ]; then
  printf 'Something is wrong with one of our services.\n'
  supervisorctl status sshd X11 xfce x11vnc novnc | tee -a /root/HEALTHCHECK_DEGRADED
  notify-send 'Healthcheck' "Failed\n$(cat /root/HEALTHCHECK_DEGRADED)" --icon=dialog-error || true
  exit 1
fi

# Then we check the expected listening ports are actually listening
for port in 22 8080; do
  if ! ss -nlt | grep -q "0.0.0.0:${port}"; then
    printf 'Nothing is listening on port %s\n' "${port}" | tee /root/HEALTHCHECK_DEGRADED
    ss -nltp | tee -a /root/HEALTHCHECK_DEGRADED
    notify-send 'Healthcheck' "Failed\n$(cat /root/HEALTHCHECK_DEGRADED)" --icon=dialog-error || true
    exit 1
  fi
done

printf "Everything looks good.\n"
if [ -f "/root/HEALTHCHECK_DEGRADED" ]; then
  rm /root/HEALTHCHECK_DEGRADED
  notify-send 'Healthcheck' 'Recovered' --icon=dialog-information || true
fi
true
